import type { Metadata } from "next";
import "./globals.css";
import Provider from "./components/Provider";
import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import "@mantine/core/styles.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <ColorSchemeScript />
      </head>
      <body>
      <MantineProvider>
        <Provider>
       {children}
        </Provider>
      </MantineProvider>
      </body>
    </html>
  );
}
